[phases.setup]
nixPkgs = ["python312", "postgresql_16.dev", "gcc"]
nixLibs = ["zlib", "stdenv.cc.cc.lib"]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install -r requirements.txt"
]
cacheDirectories = ["/root/.cache/pip"]

[start]
cmd = "gunicorn reservastoresupa.core.wsgi:application --bind 0.0.0.0:8000"
